#!/usr/bin/env python3
"""Пишет data/sim_phys.js — формулы и таблицы из physics.py."""
from __future__ import annotations
import json
from pathlib import Path
from physics import (
    G, density, float_state, pascal, ohm, jet,
    series_ph, series_iu, series_ir, series_frac, bottle_jets,
)

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "sim_phys.js"


def dumps(obj) -> str:
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


def main() -> None:
    data = {
        "G": G,
        "density": {
            "water": 1.0,
            "table": [
                ["пробка", 0.25],
                ["лёд", 0.9],
                ["вода", 1.0],
                ["стекло", 2.5],
                ["железо", 7.8],
                ["золото", 19.3],
            ],
            "demo": density(6, 3),
            "frac": series_frac(),
            "ice": float_state(0.9, 1.0),
            "iron": float_state(7.8, 1.0),
        },
        "pascal": {
            "water": series_ph(1000),
            "oil": series_ph(900),
            "kero": series_ph(800),
            "check5m": pascal(1000, 5),
            "oil2m": pascal(900, 2),
            "jets": bottle_jets(0.18),
        },
        "ohm": {
            "iu_R6": series_iu(6),
            "ir_U12": series_ir(12),
            "check": ohm(15, 5),
            "demo": ohm(12, 6),
            "taskR": ohm(20, 5) if False else {"U": 20, "I": 4, "R": 5},
        },
    }
    js = f"""/* generated by sim/build_simdata.py — не править руками */
window.PHYS = (function(){{
  const T = {dumps(data)};
  const G = {G};
  function density(m,V){{ V=+V||1e-12; const rho=(+m)/V; return {{m:+m,V:+V,rho:rho,floats:rho<1,sinks:rho>1}}; }}
  function floatState(rho, liq){{ rho=+rho; liq=+liq||1; if(rho>=liq) return {{frac:1,sink:true,note:'тонет'}}; if(rho<=0) return {{frac:0,sink:false,note:'на поверхности'}}; return {{frac:rho/liq,sink:false,note:'плавает'}}; }}
  function pascal(rho,h,g){{ g=g==null?G:g; const Pa=(+rho)*g*(+h); return {{rho:+rho,h:+h,g:g,Pa:Pa,kPa:Pa/1000}}; }}
  function ohm(U,R){{ R=+R||1e-12; const I=(+U)/R; return {{U:+U,R:+R,I:I,P:I*I*R,period:Math.max(0.28,Math.min(2.4,2/Math.max(0.25,I)))}}; }}
  function jet(fill, hole, fall){{
    fall=fall==null?0.04:fall; const depth=fill-hole; if(depth<=0) return {{v:0,range:0,pts:[]}};
    const g=9.81, v=Math.sqrt(2*g*depth), t=Math.sqrt(2*fall/g), n=18, pts=[];
    for(let i=0;i<n;i++){{ const ti=t*i/(n-1); pts.push([v*ti, Math.max(0, fall-0.5*g*ti*ti)]); }}
    return {{v:v,range:v*t,depth:depth,pts:pts}};
  }}
  return {{G,T,density,floatState,pascal,ohm,jet}};
}})();
"""
    OUT.write_text(js, encoding="utf-8")
    print("wrote", OUT, "bytes", OUT.stat().st_size)


if __name__ == "__main__":
    main()
